[project]
name = "d1-replication-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataone-cli>=3.5.2",
    "ipykernel>=6.29.5",
]
